; PlatformIO Project Configuration File

[platformio]
src_dir = 06_ble_widget/firmware

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
upload_speed = 460800
monitor_speed = 115200
lib_deps = 
    bblanchon/ArduinoJson@^7.0.0
